/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.seeseemelk.comboot;

import be.seeseemelk.comboot.connectors.TCPConnector;
import be.seeseemelk.comboot.gui.ComBootGui;

import java.io.IOException;

public class App
{

    public static void main(String[] args) throws Exception
    {
        try (
            TCPConnector connector = connect();
            ComBootServer server = new ComBootServer(connector);
        )
        {
            ComBootGui gui = new ComBootGui(server);
            gui.run();
        }
    };

    private static TCPConnector connect() throws IOException
    {
        try
        {
            for (;;)
            {
                try
                {
                    return new TCPConnector("localhost", 4444);
                }
                catch (IOException e)
                {
                    e.printStackTrace();
                    Thread.sleep(500L);
                }
            }
        }
        catch (InterruptedException e)
        {
            throw new IOException(e);
        }
    }
}
// 14 15
